name: Github Actions
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        nim-version: ['1.4.8', '1.4.x', '1.6.x', 'stable']

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: ${{ matrix.nim-version }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - run: nimble test -d:release -d:crunchyNoSimd -y
    - run: nimble test -d:release -y
    - run: nimble test --gc:orc -d:release -d:crunchyNoSimd -y
    - run: nimble test --gc:orc -d:release -y
